### ISSUE TITLE
SUPPORT FOR ANDROID N?

### ISSUE THREAD

**Issue by Ntouris3** [therealahrion/AM3D-Zirene-Sound#4]
In every ANDROID N rom i have tried AM3D does not open correctly (shows only blank screen) .  As In m, it sometimes conflicted with the prebuilt audiofx, but now there is no audiofx In the roms i tried...

**Comment by Ntouris3** [comment]
I tried with the latest magisk modules too, still not working :( ... Btw the exact version is 7.1.2

**Comment by QuantumRevenger** [comment]
I'm on N 7.1.2 (Lineage) without any problems with the module. 

The only suggestion I can think of is:

If you flashed it by TWRP without Magisk the first time and didn't perform the following steps prior to using the Magisk Modules the issues you're describing are typically an effect of this:

_* Ensure battery is at least 80%+ and suitable charger is connected._

1. Download the last known working ROM image and Magisk for installation.
- [https://tiny.cc/latestmagisk](https://tiny.cc/latestmagisk)

2. Boot into recovery mode (TWRP) and wipe - **System / Data / Dalvik Cache / Cache** Partitions.

3. Install the ROM Zip (afterward go back to the menu - **do not boot into the system yet.**)

4. Install the latest Magisk Zip and then boot into system.

5. **Allow up to a full hour whilst android is preparing the system as a precaution.**

6. Open pre-installed browser and fetch the latest Magisk Manager from [https://tiny.cc/latestmanager](https://tiny.cc/latestmanager)

7. Allow the installation from unknown sources and install the APK file.

8. Using Magisk Manager, download, and install the following modules:
**_After installing a module, reboot prior to the next. Otherwise, Magisk sometimes goes wrong._**

- Ainur JamesDSP
- AM3D and/or Dolby Atmos Classic (Lenovo A7000) [6.5]
- Universal Deep_Buffer Remover

9. Perform a system shutdown and charge your phone until full. After, switch-on your device.

Everything should be working sweet & sound, if not maybe look into SELinux? (Also try plain Lineage OS, if problems persist with custom ROM.)

**Comment by Zackptg5** [comment]
There's a certain lib and rom framework that is only part of the audio flinger (forget what they are). Most nougat roms don't have this and is why it doesn't work for you.

**Comment by Ntouris3** [comment]
Do you remember those things?

**Comment by martmists** [comment]
Does anyone have this lib/framework so we can make a magisk module for it?
